### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by PaulHost** [janpio/ionic-epubjs#13]
If create another page to open home.ts it getting crash. Same problem with sidemenu.
Can it be fix somehow? May be I need somehow to use ePub.js in whole project?

**Comment by janpio** [comment]
What exactly did you do? ePub.js is included in the index.html and so should be available everywhere - but the code has to match.

**Comment by PaulHost** [comment]
lets try to create slidemenu or segue to home.ts from another_page.ts

**Comment by janpio** [comment]
I am not sure I understood what you wrote, but check the project now. I renamed HomePage to BookPage and added a new HomePage where you can choose a book to be shown. Did you mean something like that?

**Comment by PaulHost** [comment]
yes! Thanks
