### ISSUE TITLE
book.all.ready promise is not giving result nor causes any error

### ISSUE THREAD

**Issue by kama1** [janpio/ionic-epubjs#3]
this.book.all.ready.then(foo =>{
        console.log('ready', foo);
      }).catch(error => {
        console.log(error);
      });

not logging anything
take a look at: https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks

**Comment by janpio** [comment]
I don't see `ready` anywhere on that page. Wrong link?

`this.book.ready.all.then(...` from my code fires instantly though. (You have to pull my updates, I fixed the stuff you pushed via PR to me)
